### ISSUE TITLE
Cant enable Imported Flow - Premium Connector?

### ISSUE THREAD

**Issue by jgriffiths014** [russrimm/AADAppSecretsnCertsExpirationNotification#1]
I get an error stating that the user doesn't have a license for non-standard plan, but what premium connector is in use here? the only one I could think of was Send Email, which I exchanged for SendGrid, and have successfully used in other flows. I have an office 365 E3 license.

**Comment by russrimm** [comment]
@jgriffiths014 it's using the HTTP connector which is premium.  I've created a new ARM template that deploys a Logic App version of the same process if you're interested in trying that.  That would use Azure consumption vs requiring a Power Automate premium license.

**Comment by paulmortlock** [comment]
Unable to import I see it after choosing the file but the import button is greyed out?
